---
apiVersion: v1
kind: Service
metadata:
  name: ktcloud-svc
spec:
  selector:
    color: blue
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktcloud-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      color: blue
  template:
    metadata:
      labels:
        color: blue
    spec:
      containers:
        - name: ktcloudctn-blue
          image: zmflspa123/ktcloudinfra:blue
          resources:
            limits:
              memory: "32Mi"
              cpu: "250m"
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktcloud-green
spec:
  replicas: 1
  selector:
    matchLabels:
      color: green
  template:
    metadata:
      labels:
        color: green
    spec:
      containers:
        - name: ktcloudctn-green
          image: zmflspa123/ktcloudinfra:green
          resources:
            limits:
              memory: "32Mi"
              cpu: "250m"
          ports:
            - containerPort: 80

