---
apiVersion: v1
kind: Service
metadata:
  name: ktcloud-svc
spec:
  selector:
    color: blue
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktcloud-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      color: blue
  template:
    metadata:
      labels:
        color: blue
    spec:
      containers:
        - name: ktcloudctn-blue
          image: zmflspa123/ktcloudinfra:blue
          resources:
            limits:
              memory: "32Mi"
              cpu: "250m"
          ports:
            - containerPort: 80
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cron-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: ktcloud-blue
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 3
  maxReplicaCount: 6
  triggers:
    - type: cron
      metadata:
        timezone: "Asia/Seoul"
        start: "46 * * * *"
        end: "50 * * * *"
        desiredReplicas: "6"


